export const hotelTypes = [
  "Budget",
  "Boutique",
  "Luxury",
  "Business",
  "Family",
  "Hiking Resort",
  "Cabin",
  "Beach Resort",
  "Golf Resort",
  "Motel",
  "All Inclusive",
  "Pet Friendly",
  "Self Catering",
];

export const hotelFacilities = [
  "Free WiFi",
  "Parking",
  "Airport Shuttle",
  "Family Rooms",
  "Non-Smoking Rooms",
  "Outdoor Pool",
  "Spa & Hammam",
  "Fitness Center",
  "Prayer Room",
  "Nearby Clinic",
  "Local Cuisine Restaurant",
  "Coffee and Tea Lounge",
  "Kids' Play Area",
  "24/7 Security",
  "Air Conditioning",
  "Taxi Service",
];
